<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\City;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            ['state_id' => 4, 'county_id' => 1, 'name' => 'Stuttgart', 'code' => '01-01', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 1, 'name' => 'De Witt', 'code' => '01-02', 'tax_rate' => 3.5],
            ['state_id' => 4, 'county_id' => 1, 'name' => 'Humphrey', 'code' => '01-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 1, 'name' => 'Gillett', 'code' => '01-04', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 1, 'name' => 'Almyra', 'code' => '01-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 1, 'name' => 'Saint Charles', 'code' => '01-06', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 2, 'name' => 'Crossett', 'code' => '02-01', 'tax_rate' => 1.75],
            ['state_id' => 4, 'county_id' => 2, 'name' => 'Fountain Hill', 'code' => '02-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 2, 'name' => 'Hamburg', 'code' => '02-03', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 2, 'name' => 'Parkdale', 'code' => '02-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 2, 'name' => 'Portland', 'code' => '02-06', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 2, 'name' => 'Wilmont', 'code' => '02-07', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 3, 'name' => 'Mountain Home', 'code' => '03-01', 'tax_rate' => 2.125],
            ['state_id' => 4, 'county_id' => 3, 'name' => 'Cotter', 'code' => '03-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 3, 'name' => 'Gassville', 'code' => '03-03', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 3, 'name' => 'Norfork', 'code' => '03-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 3, 'name' => 'Lakeview', 'code' => '03-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 3, 'name' => 'Big Flat', 'code' => '03-06', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 3, 'name' => 'Salesville', 'code' => '03-07', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 3, 'name' => 'Briarcliff', 'code' => '03-09', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Siloam Springs', 'code' => '04-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Rogers', 'code' => '04-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Bentonville', 'code' => '04-03', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Decatur', 'code' => '04-05', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Gentry', 'code' => '04-06', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Gravette', 'code' => '04-07', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Lowell', 'code' => '04-08', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Centerton', 'code' => '04-09', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Pea Ridge', 'code' => '04-10', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Cave Springs', 'code' => '04-11', 'tax_rate' => 2.25],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Sulphur Springs', 'code' => '04-12', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Avoca', 'code' => '04-13', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Garfield', 'code' => '04-14', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Highfill', 'code' => '04-16', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Little Flock', 'code' => '04-17', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Springtown', 'code' => '04-21', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 4, 'name' => 'Bella Vista', 'code' => '04-23', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 5, 'name' => 'Alpena', 'code' => '05-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 5, 'name' => 'Lead Hill', 'code' => '05-07', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 5, 'name' => 'Harrison', 'code' => '05-12', 'tax_rate' => 1.75],
            ['state_id' => 4, 'county_id' => 5, 'name' => 'Diamond City', 'code' => '05-15', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 6, 'name' => 'Banks', 'code' => '06-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 6, 'name' => 'Hermitage', 'code' => '06-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 6, 'name' => 'Warren', 'code' => '06-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 7, 'name' => 'Hampton', 'code' => '07-01', 'tax_rate' => 0.5],
            ['state_id' => 4, 'county_id' => 7, 'name' => 'Thornton', 'code' => '07-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 8, 'name' => 'Eureka Springs', 'code' => '08-01', 'tax_rate' => 2.375],
            ['state_id' => 4, 'county_id' => 8, 'name' => 'Berryville', 'code' => '08-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 8, 'name' => 'Green Forest', 'code' => '08-03', 'tax_rate' => 2.25],
            ['state_id' => 4, 'county_id' => 8, 'name' => 'Oak Grove', 'code' => '08-13', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 9, 'name' => 'Lake Village', 'code' => '09-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 9, 'name' => 'Eudora', 'code' => '09-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 9, 'name' => 'Dermott', 'code' => '09-03', 'tax_rate' => 4],
            ['state_id' => 4, 'county_id' => 10, 'name' => 'Caddo Valley', 'code' => '10-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 10, 'name' => 'Arkadelphia', 'code' => '10-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 10, 'name' => 'Gurdon', 'code' => '10-03', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 10, 'name' => 'Amity', 'code' => '10-04', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 10, 'name' => 'Gum Springs', 'code' => '10-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 11, 'name' => 'Corning', 'code' => '11-01', 'tax_rate' => 1.75],
            ['state_id' => 4, 'county_id' => 11, 'name' => 'Rector', 'code' => '11-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 11, 'name' => 'Piggott', 'code' => '11-03', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 11, 'name' => 'Polland', 'code' => '11-10', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 12, 'name' => 'Concord', 'code' => '12-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 12, 'name' => 'Greers Ferry', 'code' => '12-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 12, 'name' => 'Heber Springs', 'code' => '12-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 12, 'name' => 'Quitman', 'code' => '12-05', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 13, 'name' => 'Rison', 'code' => '13-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 13, 'name' => 'Kingsland', 'code' => '13-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 14, 'name' => 'Emerson', 'code' => '14-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 14, 'name' => 'Mc Neil', 'code' => '14-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 14, 'name' => 'Magnolia', 'code' => '14-03', 'tax_rate' => 2.25],
            ['state_id' => 4, 'county_id' => 14, 'name' => 'Taylor', 'code' => '14-04', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 15, 'name' => 'Morrilton', 'code' => '15-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 15, 'name' => 'Menifee', 'code' => '15-02', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 15, 'name' => 'Oppelo', 'code' => '15-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 15, 'name' => 'Plumerville', 'code' => '15-04', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 16, 'name' => 'Bay', 'code' => '16-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 16, 'name' => 'Bono', 'code' => '16-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 16, 'name' => 'Brookland', 'code' => '16-04', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 16, 'name' => 'Caraway', 'code' => '16-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 16, 'name' => 'Cash', 'code' => '16-06', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 16, 'name' => 'Lake City', 'code' => '16-09', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 16, 'name' => 'Monette', 'code' => '16-10', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 16, 'name' => 'Jonesboro', 'code' => '16-11', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 17, 'name' => 'Alma', 'code' => '17-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 17, 'name' => 'Van Buren', 'code' => '17-02', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 17, 'name' => 'Mulberry', 'code' => '17-03', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 17, 'name' => 'Mountainburg', 'code' => '17-04', 'tax_rate' => 2.5],
            ['state_id' => 4, 'county_id' => 17, 'name' => 'Kibler', 'code' => '17-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 17, 'name' => 'Dyer', 'code' => '17-07', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 17, 'name' => 'Rudy', 'code' => '17-09', 'tax_rate' => 0.5],
            ['state_id' => 4, 'county_id' => 17, 'name' => 'Cedarville', 'code' => '17-10', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 18, 'name' => 'Marion', 'code' => '18-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 18, 'name' => 'West Memphis', 'code' => '18-02', 'tax_rate' => 2.25],
            ['state_id' => 4, 'county_id' => 18, 'name' => 'Earle', 'code' => '18-03', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 18, 'name' => 'Crawfordsville', 'code' => '18-04', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 18, 'name' => 'Gilmore', 'code' => '18-06', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 18, 'name' => 'Jennette', 'code' => '18-08', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 18, 'name' => 'Sunset', 'code' => '18-10', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 18, 'name' => 'Turrell', 'code' => '18-11', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 18, 'name' => 'Anthonyville', 'code' => '18-12', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 19, 'name' => 'Cherry Valley', 'code' => '19-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 19, 'name' => 'Hickory Ridge', 'code' => '19-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 19, 'name' => 'Parkin', 'code' => '19-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 19, 'name' => 'Wynne', 'code' => '19-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 20, 'name' => 'Sparkman', 'code' => '20-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 20, 'name' => 'Fordyce', 'code' => '20-02', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 20, 'name' => 'Carthage', 'code' => '20-03', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 21, 'name' => 'Mc Gehee', 'code' => '21-01', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 21, 'name' => 'Arkansas City', 'code' => '21-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 21, 'name' => 'Dumas', 'code' => '21-03', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 22, 'name' => 'Monticello', 'code' => '22-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 22, 'name' => 'Tillar', 'code' => '22-03', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 22, 'name' => 'Wilmar', 'code' => '22-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 23, 'name' => 'Conway', 'code' => '23-01', 'tax_rate' => 1.75],
            ['state_id' => 4, 'county_id' => 23, 'name' => 'Mayflower', 'code' => '23-02', 'tax_rate' => 2.5],
            ['state_id' => 4, 'county_id' => 23, 'name' => 'Greenbrier', 'code' => '23-03', 'tax_rate' => 2.5],
            ['state_id' => 4, 'county_id' => 23, 'name' => 'Vilonia', 'code' => '23-04', 'tax_rate' => 2.75],
            ['state_id' => 4, 'county_id' => 23, 'name' => 'Damascus', 'code' => '23-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 23, 'name' => 'Guy', 'code' => '23-07', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 24, 'name' => 'Branch', 'code' => '24-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 24, 'name' => 'Wiederkehr Village', 'code' => '24-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 24, 'name' => 'Altus', 'code' => '24-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 24, 'name' => 'Charleston', 'code' => '24-05', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 24, 'name' => 'Ozark', 'code' => '24-07', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 25, 'name' => 'Mammoth Spring', 'code' => '25-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 25, 'name' => 'Salem', 'code' => '25-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 25, 'name' => 'Viola', 'code' => '25-03', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 26, 'name' => 'Hot Springs', 'code' => '26-01', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 27, 'name' => 'Sheridan', 'code' => '27-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 28, 'name' => 'Marmaduke', 'code' => '28-03', 'tax_rate' => 1.25],
            ['state_id' => 4, 'county_id' => 28, 'name' => 'Oak Grove Heights', 'code' => '28-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 28, 'name' => 'Paragould', 'code' => '28-05', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 29, 'name' => 'Hope', 'code' => '29-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 29, 'name' => 'Blevins', 'code' => '29-02', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 29, 'name' => 'McCaskill', 'code' => '29-05', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 29, 'name' => 'Patmos', 'code' => '29-08', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 29, 'name' => 'Washington', 'code' => '29-10', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 29, 'name' => 'McNab', 'code' => '29-11', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 30, 'name' => 'Malvern', 'code' => '30-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 30, 'name' => 'Perla', 'code' => '30-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 30, 'name' => 'Rockport', 'code' => '30-03', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 31, 'name' => 'Nashville', 'code' => '31-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 31, 'name' => 'Dierks', 'code' => '31-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 31, 'name' => 'Mineral Springs', 'code' => '31-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 32, 'name' => 'Batesville', 'code' => '32-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 32, 'name' => 'Cushman', 'code' => '32-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 32, 'name' => 'Moorefield', 'code' => '32-05', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 32, 'name' => 'Pleasant Plains', 'code' => '32-08', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 33, 'name' => 'Horseshoe Bend', 'code' => '33-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 33, 'name' => 'Melbourne', 'code' => '33-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 33, 'name' => 'Calico Rock', 'code' => '33-03', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 33, 'name' => 'Pineville', 'code' => '33-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 33, 'name' => 'Franklin', 'code' => '33-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 33, 'name' => 'Oxford', 'code' => '33-06', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 33, 'name' => 'Guion', 'code' => '33-07', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 34, 'name' => 'Newport', 'code' => '34-01', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 34, 'name' => 'Tuckerman', 'code' => '34-02', 'tax_rate' => 1.25],
            ['state_id' => 4, 'county_id' => 34, 'name' => 'Beedeville', 'code' => '34-05', 'tax_rate' => 0.5],
            ['state_id' => 4, 'county_id' => 34, 'name' => 'Diaz', 'code' => '34-07', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 34, 'name' => 'Swifton', 'code' => '34-09', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 35, 'name' => 'Pine Bluff', 'code' => '35-01', 'tax_rate' => 1.625],
            ['state_id' => 4, 'county_id' => 35, 'name' => 'Wabbaseka', 'code' => '35-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 35, 'name' => 'White Hall', 'code' => '35-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 35, 'name' => 'Redfield', 'code' => '35-04', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 35, 'name' => 'Altheimer', 'code' => '35-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 35, 'name' => 'Sherrill', 'code' => '35-07', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 36, 'name' => 'Clarksville', 'code' => '36-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 36, 'name' => 'Coal Hill', 'code' => '36-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 36, 'name' => 'Lamar', 'code' => '36-05', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 37, 'name' => 'Bradley', 'code' => '37-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 37, 'name' => 'Stamps', 'code' => '37-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 37, 'name' => 'Lewisville', 'code' => '37-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 38, 'name' => 'Walnut Ridge', 'code' => '38-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 38, 'name' => 'Black Rock', 'code' => '38-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 38, 'name' => 'Hoxie', 'code' => '38-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 38, 'name' => 'Imboden', 'code' => '38-06', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 38, 'name' => 'Portia', 'code' => '38-09', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 38, 'name' => 'Powhatan', 'code' => '38-10', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 38, 'name' => 'Ravenden', 'code' => '38-11', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 39, 'name' => 'Marianna', 'code' => '39-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 39, 'name' => 'Moro', 'code' => '39-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 40, 'name' => 'Star City', 'code' => '40-01', 'tax_rate' => 1.25],
            ['state_id' => 4, 'county_id' => 40, 'name' => 'Gould', 'code' => '40-02', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 40, 'name' => 'Grady', 'code' => '40-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 41, 'name' => 'Ashdown', 'code' => '41-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 41, 'name' => 'Wilton', 'code' => '41-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 41, 'name' => 'Foreman', 'code' => '41-07', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 42, 'name' => 'Blue Mountain', 'code' => '42-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 42, 'name' => 'Magazine', 'code' => '42-04', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 42, 'name' => 'Morrison Bluff', 'code' => '42-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 42, 'name' => 'Paris', 'code' => '42-06', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 42, 'name' => 'Scranton', 'code' => '42-08', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 42, 'name' => 'Subiaco', 'code' => '42-09', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 42, 'name' => 'Booneville', 'code' => '42-10', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 43, 'name' => 'Austin', 'code' => '43-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 43, 'name' => 'Carlisle', 'code' => '43-04', 'tax_rate' => 2.125],
            ['state_id' => 4, 'county_id' => 43, 'name' => 'England', 'code' => '43-06', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 43, 'name' => 'Humnoke', 'code' => '43-07', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 43, 'name' => 'Keo', 'code' => '43-08', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 43, 'name' => 'Lonoke', 'code' => '43-09', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 43, 'name' => 'Ward', 'code' => '43-10', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 43, 'name' => 'Cabot', 'code' => '43-11', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 44, 'name' => 'Huntsville', 'code' => '44-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 44, 'name' => 'Saint Paul', 'code' => '44-03', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 45, 'name' => 'Bull Shoals', 'code' => '45-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 45, 'name' => 'Flippin', 'code' => '45-02', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 45, 'name' => 'Pyatt', 'code' => '45-03', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 45, 'name' => 'Summit', 'code' => '45-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 45, 'name' => 'Yellville', 'code' => '45-05', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 46, 'name' => 'Garland', 'code' => '46-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 46, 'name' => 'Fouke', 'code' => '46-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 46, 'name' => 'Texarkana', 'code' => '46-13', 'tax_rate' => 2.5],
            ['state_id' => 4, 'county_id' => 47, 'name' => 'Osceola', 'code' => '47-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 47, 'name' => 'Keiser', 'code' => '47-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 47, 'name' => 'Blytheville', 'code' => '47-05', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 47, 'name' => 'Gosnell', 'code' => '47-09', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 47, 'name' => 'Joiner', 'code' => '47-10', 'tax_rate' => 1.25],
            ['state_id' => 4, 'county_id' => 47, 'name' => 'Leachville', 'code' => '47-11', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 47, 'name' => 'Luxora', 'code' => '47-12', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 47, 'name' => 'Manila', 'code' => '47-13', 'tax_rate' => 1.25],
            ['state_id' => 4, 'county_id' => 47, 'name' => 'Wilson', 'code' => '47-16', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 47, 'name' => 'Etowah', 'code' => '47-17', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 48, 'name' => 'Clarendon', 'code' => '48-01', 'tax_rate' => 4],
            ['state_id' => 4, 'county_id' => 48, 'name' => 'Brinkley', 'code' => '48-02', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 48, 'name' => 'Holly Grove', 'code' => '48-03', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 48, 'name' => 'Roe', 'code' => '48-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 49, 'name' => 'Norman', 'code' => '49-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 49, 'name' => 'Mount Ida', 'code' => '49-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 50, 'name' => 'Prescott', 'code' => '50-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 50, 'name' => 'Rosston', 'code' => '50-06', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 51, 'name' => 'Jasper', 'code' => '51-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 51, 'name' => 'Western Grove', 'code' => '51-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 52, 'name' => 'Camden', 'code' => '52-01', 'tax_rate' => 1.75],
            ['state_id' => 4, 'county_id' => 52, 'name' => 'Stephens', 'code' => '52-02', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 52, 'name' => 'East Camden', 'code' => '52-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 52, 'name' => 'Bearden', 'code' => '52-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 52, 'name' => 'Childester', 'code' => '52-05', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 53, 'name' => 'Perryville', 'code' => '53-07', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 54, 'name' => 'Marvell', 'code' => '54-05', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 54, 'name' => 'Helena-West Helena', 'code' => '54-07', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 55, 'name' => 'Delight', 'code' => '55-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 55, 'name' => 'Glenwood', 'code' => '55-04', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 55, 'name' => 'Murfreesboro', 'code' => '55-05', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 56, 'name' => 'Lepanto', 'code' => '56-01', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 56, 'name' => 'Harrisburg', 'code' => '56-03', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 56, 'name' => 'Marked Tree', 'code' => '56-04', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 56, 'name' => 'Trumann', 'code' => '56-05', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 56, 'name' => 'Tyronza', 'code' => '56-06', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 56, 'name' => 'Weiner', 'code' => '56-08', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 56, 'name' => 'Waldenburg', 'code' => '56-09', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 57, 'name' => 'Mena', 'code' => '57-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 57, 'name' => 'Cove', 'code' => '57-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 57, 'name' => 'Grannis', 'code' => '57-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 57, 'name' => 'Hatfield', 'code' => '57-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 57, 'name' => 'Vandervoort', 'code' => '57-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 57, 'name' => 'Wickes', 'code' => '57-07', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 58, 'name' => 'Russellville', 'code' => '58-01', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 58, 'name' => 'Atkins', 'code' => '58-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 58, 'name' => 'Dover', 'code' => '58-03', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 58, 'name' => 'Hector', 'code' => '58-04', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 58, 'name' => 'London', 'code' => '58-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 58, 'name' => 'Pottsville', 'code' => '58-06', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 59, 'name' => 'Hazen', 'code' => '59-01', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 59, 'name' => 'Des Arc', 'code' => '59-03', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 59, 'name' => 'De Valls Bluff', 'code' => '59-04', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 60, 'name' => 'North Little Rock', 'code' => '60-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 60, 'name' => 'Alexander', 'code' => '60-02', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 60, 'name' => 'Jacksonville', 'code' => '60-04', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 60, 'name' => 'Little Rock', 'code' => '60-05', 'tax_rate' => 1.125],
            ['state_id' => 4, 'county_id' => 60, 'name' => 'Maumelle', 'code' => '60-06', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 60, 'name' => 'Sherwood', 'code' => '60-07', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 61, 'name' => 'Maynard', 'code' => '61-02', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 61, 'name' => 'Pocahontas', 'code' => '61-04', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 62, 'name' => 'Bryant', 'code' => '62-01', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 62, 'name' => 'Shannon Hills', 'code' => '62-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 62, 'name' => 'Benton', 'code' => '62-03', 'tax_rate' => 2.5],
            ['state_id' => 4, 'county_id' => 62, 'name' => 'Bauxite', 'code' => '62-04', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 62, 'name' => 'Haskell', 'code' => '62-05', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 63, 'name' => 'Waldron', 'code' => '63-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 64, 'name' => 'Gilbert', 'code' => '64-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 64, 'name' => 'Leslie', 'code' => '64-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 64, 'name' => 'Marshall', 'code' => '64-03', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 65, 'name' => 'Fort Smith', 'code' => '65-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 65, 'name' => 'Huntington', 'code' => '65-02', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 65, 'name' => 'Mansfield', 'code' => '65-03', 'tax_rate' => 2.5],
            ['state_id' => 4, 'county_id' => 65, 'name' => 'Barling', 'code' => '65-04', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 65, 'name' => 'Greenwood', 'code' => '65-05', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 65, 'name' => 'Bonanza', 'code' => '65-06', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 65, 'name' => 'Hackett', 'code' => '65-09', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 65, 'name' => 'Hartford', 'code' => '65-10', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 65, 'name' => 'Midland', 'code' => '65-12', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 66, 'name' => 'De Queen', 'code' => '66-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 66, 'name' => 'Gillham', 'code' => '66-03', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 66, 'name' => 'Horatio', 'code' => '66-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 66, 'name' => 'Lockesburg', 'code' => '66-05', 'tax_rate' => 0.75],
            ['state_id' => 4, 'county_id' => 67, 'name' => 'Hardy', 'code' => '67-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 67, 'name' => 'Ash Flat', 'code' => '67-02', 'tax_rate' => 1.375],
            ['state_id' => 4, 'county_id' => 67, 'name' => 'Cave City', 'code' => '67-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 67, 'name' => 'Evening Shade', 'code' => '67-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 67, 'name' => 'Cherokee Village', 'code' => '67-08', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 67, 'name' => 'Highland', 'code' => '67-09', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 68, 'name' => 'Hughes', 'code' => '68-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 68, 'name' => 'Forrest City', 'code' => '68-02', 'tax_rate' => 1.875],
            ['state_id' => 4, 'county_id' => 68, 'name' => 'Wheatley', 'code' => '68-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 68, 'name' => 'Palestine', 'code' => '68-04', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 68, 'name' => 'Madison', 'code' => '68-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 68, 'name' => 'Colt', 'code' => '68-07', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 68, 'name' => 'Widener', 'code' => '68-08', 'tax_rate' => 1.75],
            ['state_id' => 4, 'county_id' => 69, 'name' => 'Mountain View', 'code' => '69-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 70, 'name' => 'El Dorado', 'code' => '70-02', 'tax_rate' => 1.25],
            ['state_id' => 4, 'county_id' => 70, 'name' => 'Junction City', 'code' => '70-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 70, 'name' => 'Strong', 'code' => '70-08', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 71, 'name' => 'Shirley', 'code' => '71-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 71, 'name' => 'Clinton', 'code' => '71-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 71, 'name' => 'Fairfield Bay', 'code' => '71-04', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'Elkins', 'code' => '72-02', 'tax_rate' => 2.75],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'Elm Springs', 'code' => '72-03', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'Goshen', 'code' => '72-05', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'Greenland', 'code' => '72-06', 'tax_rate' => 4.5],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'Johnson', 'code' => '72-07', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'Praire Grove', 'code' => '72-09', 'tax_rate' => 2.75],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'Springdale', 'code' => '72-10', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'Tonitown', 'code' => '72-11', 'tax_rate' => 2.75],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'West Fork', 'code' => '72-12', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'Winslow', 'code' => '72-13', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'Fayetteville', 'code' => '72-14', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'Lincoln', 'code' => '72-15', 'tax_rate' => 3],
            ['state_id' => 4, 'county_id' => 72, 'name' => 'Farmington', 'code' => '72-16', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 73, 'name' => 'Rose Bud', 'code' => '73-01', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 73, 'name' => 'Beebe', 'code' => '73-02', 'tax_rate' => 1.25],
            ['state_id' => 4, 'county_id' => 73, 'name' => 'Bradford', 'code' => '73-03', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 73, 'name' => 'Kensett', 'code' => '73-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 73, 'name' => 'Higginson', 'code' => '73-09', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 73, 'name' => 'Judsonia', 'code' => '73-10', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 73, 'name' => 'Mc Rae', 'code' => '73-12', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 73, 'name' => 'Pangburn', 'code' => '73-13', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 73, 'name' => 'Searcy', 'code' => '73-15', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 73, 'name' => 'Bald Knob', 'code' => '73-17', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 74, 'name' => 'Cotton Plant', 'code' => '74-01', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 74, 'name' => 'Augusta', 'code' => '74-02', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 74, 'name' => 'McCrory', 'code' => '74-04', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 74, 'name' => 'Patterson', 'code' => '74-05', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 75, 'name' => 'Plainview', 'code' => '75-01', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 75, 'name' => 'Dardanelle', 'code' => '75-02', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 75, 'name' => 'Ola', 'code' => '75-03', 'tax_rate' => 2],
            ['state_id' => 4, 'county_id' => 75, 'name' => 'Danville', 'code' => '75-04', 'tax_rate' => 1.5],
            ['state_id' => 4, 'county_id' => 75, 'name' => 'Belleville', 'code' => '75-06', 'tax_rate' => 1],
            ['state_id' => 4, 'county_id' => 75, 'name' => 'Havana', 'code' => '75-07', 'tax_rate' => 1],
        ];

        foreach ($cities as $city) {
            City::updateOrCreate(
                ['code' => $city['code']],
                ['state_id' => $city['state_id'], 'county_id' => $city['county_id'], 'name' => $city['name'], 'tax_rate' => $city['tax_rate']]
            );
        }
    }
}
